### ISSUE TITLE
gpuR installation error Ubuntu 18.04. unknown OpenCL error

### ISSUE THREAD

**Issue by evodevosys** [cdeterman/gpuR#148] opened 2019-01-12 07:29 UTC
I've followed the installation instructions in the  wiki for Linux including installing the various Nvidia drivers, but am having the error below.  

[after a bunch of compiling]
** R
** inst
** byte-compile and prepare package for lazy loading
Creating a generic function for ‘eigen’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘%o%’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘nrow’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘ncol’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘crossprod’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘tcrossprod’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘cov’ from package ‘stats’ in package ‘gpuR’
Creating a generic function for ‘colSums’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘rowSums’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘colMeans’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘rowMeans’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘dist’ from package ‘stats’ in package ‘gpuR’
Creating a generic function for ‘diag’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘diag<-’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘det’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘norm’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘qr.R’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘qr.Q’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘typeof’ from package ‘base’ in package ‘gpuR’
Creating a generic function for ‘colnames<-’ from package ‘base’ in package ‘gpuR’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘gpuR’:
 .onAttach failed in attachNamespace() for 'gpuR', details:
  call: initContexts()
  error: ViennaCL: FATAL ERROR: ViennaCL encountered an unknown OpenCL error. Most likely your OpenCL SDK or driver is not installed properly. In some cases, this error is due to an invalid global work size or several kernel compilation errors.
If you think that this is a bug in ViennaCL, please report it at viennacl-support@lists.sourceforge.net and supply at least the following information:
 * Operating System
 * Which OpenCL implementation (AMD, NVIDIA, etc.)
 * ViennaCL version
Many thanks in advance!
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/user/R/x86_64-pc-linux-gnu-library/3.5/gpuR’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/Rtmp0vDmyr/file34826bcb5f14/gpuR_2.0.1.tar.gz’ had non-zero exit status
> `

Notably, the was in installing gpuR.  installing RViennaCL worked just fine - at least it gave no errors.  I get this error both when installing gpuR from CRAN and also when trying from github using devtools  (the development package downloaded today for both gpuR and RViennaCL).

Thanks for any help,
Scott

**Comment by cdeterman** [comment] 2019-01-14 16:45
@evodevosys can you trying installing `apt-get install nvidia-opencl-icd`?  See if that helps you.  Also, did you set any flags prior to compilation (e.g. `OPENCL_LIB`)?

**Comment by evodevosys** [comment] 2019-01-14 17:26
@cdeterman When I tried the nvidia-opencl-icd it gave me:

```
Package nvidia-opencl-icd is a virtual package provided by:
  libnvidia-compute-410 410.78-0ubuntu1~18.04~pop0
  nvidia-opencl-icd-340 340.107-0ubuntu0.18.04.1
You should explicitly select one to install.
```

My nvidia cuda version is 410 so I tried installing that one, but it says it is already the newest version (I suspect it is probably installed with the cuda toolkit from [here](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal)

I didn't set any OPENCL flags explicitly but it looks like it used defaults for some settings.
When trying to install gpuR, this is the first part of the output:
-------------------------------
```
* installing *source* package 'gpuR' ...
** package 'gpuR' successfully unpacked and MD5 sums checked
OPENCL_FLAGS not set, using default -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS  -DCL_HPP_TARGET_OPENCL_VERSION=120
Linux OS
found OpenCL library
Checking OpenCL C++ API
OPENCL_INC not set, using default include directory /usr/include
cl2.hpp header exists

*********** Generated Makevars file ***********
CXX_STD=CXX11
PKG_CPPFLAGS=-I../inst/include -DCL_HPP_MINIMUM_OPENCL_VERSION=110 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_HPP_TARGET_OPENCL_VERSION=120 -fPIC -I'/usr/include/' -DHAVE_CL_CL2_HPP
PKG_CXXFLAGS=
PKG_LIBS=-lOpenCL
BUILD_LIB=

$(SHLIB): $(BUILD_LIB)

../inst/include/loader/libOpenCL.a:
	cd ../inst/include/loader/ && $(MAKE) libOpenCL.a \
	CC="$(CC)" CFLAGS="$(ALL_CFLAGS)" AR="$(AR)" RM="$(RM)" \
	ICD_OS=icd_linux
```
***********************************************

**Comment by evodevosys** [comment] 2019-01-14 17:32
The last one just before it installs it to the R libs directory is:

`g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o gpuR.so RcppExports.o chol.o context.o custom_math.o device.o gpuEigenPtr.o gpuMatrix_igemm.o norm.o platform.o set_row_order.o solve.o synchronize.o trunc_gpuMat.o utils-vcl.o utils.o vclPtr.o vienna_blas1.o vienna_blas2.o vienna_blas3.o vienna_eigen.o vienna_qr.o vienna_stats.o vienna_svd.o -lOpenCL -L/usr/lib/R/lib -lR`

**Comment by cdeterman** [comment] 2019-01-14 17:38
Hmm..., one more thing then.  Could you provide the output from the following command.  I want to see where the `libOpenCL.so` is on your machine.

`ldconfig -p | grep 'libOpenCL\|lOpenCL'`

**Comment by evodevosys** [comment] 2019-01-14 17:41
`$ ldconfig -p | grep 'libOpenCL\|lOpenCL'
	libOpenCL.so.1 (libc6,x86-64) => /usr/local/cuda-10.0/targets/x86_64-linux/lib/libOpenCL.so.1
	libOpenCL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
	libOpenCL.so (libc6,x86-64) => /usr/local/cuda-10.0/targets/x86_64-linux/lib/libOpenCL.so
	libOpenCL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libOpenCL.so
`

**Comment by cdeterman** [comment] 2019-01-14 18:00
Ok, here's another test.  Clone my [intel_opencl](https://github.com/cdeterman/intel_opencl) repository

```sh
git clone https://github.com/cdeterman/intel_opencl
```

Then try to compile that script with the following.

```sh
g++ -o clDeviceQuery -I/usr/include clDeviceQuery.cpp -lOpenCL
```
Then run it

```sh
./clDeviceQuery
```

If that doesn't work, try linking directly to your `libOpenCL.so`

```sh
g++ -o clDeviceQuery -I/usr/include clDeviceQuery.cpp -L/usr/local/cuda-10.0/targets/x86_64/lib/ -lOpenCL
```

**Comment by evodevosys** [comment] 2019-01-14 18:05
I got errors (and several warnings) in both of those.  Here is complete output:

`~/Downloads/intel_opencl$  [master] $ g++ -o clDeviceQuery -I/usr/include clDeviceQuery.cpp -lOpenCL
clDeviceQuery.cpp: In function ‘void clPrintDevInfo(cl_device_id)’:
clDeviceQuery.cpp:54:70: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("  CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:\t%u\n", workitem_dims);
                                                                      ^
clDeviceQuery.cpp:59:115: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("  CL_DEVICE_MAX_WORK_ITEM_SIZES:\t%u / %u / %u \n", workitem_size[0], workitem_size[1], workitem_size[2]);
                                                               ~~~~~~~~~~~~~~~~                                    ^
clDeviceQuery.cpp:59:115: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
clDeviceQuery.cpp:59:115: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
clDeviceQuery.cpp:64:66: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("  CL_DEVICE_MAX_WORK_GROUP_SIZE:\t%u\n", workgroup_size);
                                                                  ^
clDeviceQuery.cpp:131:51: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("\t\t\t2D_MAX_WIDTH\t %u\n", szMaxDims[0]);
                                       ~~~~~~~~~~~~^
clDeviceQuery.cpp:133:56: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("\t\t\t\t\t2D_MAX_HEIGHT\t %u\n", szMaxDims[1]);
                                            ~~~~~~~~~~~~^
clDeviceQuery.cpp:135:55: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("\t\t\t\t\t3D_MAX_WIDTH\t %u\n", szMaxDims[2]);
                                           ~~~~~~~~~~~~^
clDeviceQuery.cpp:137:56: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("\t\t\t\t\t3D_MAX_HEIGHT\t %u\n", szMaxDims[3]);
                                            ~~~~~~~~~~~~^
clDeviceQuery.cpp:139:55: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("\t\t\t\t\t3D_MAX_DEPTH\t %u\n", szMaxDims[4]);
                                           ~~~~~~~~~~~~^

~/Downloads/intel_opencl$  [master] $ ./clDeviceQuery 
clDeviceQuery Starting...

 Error -1001 in clGetPlatformIDs Call!

~/Downloads/intel_opencl$  [master] $ g++ -o clDeviceQuery -I/usr/include clDeviceQuery.cpp -L/usr/local/cuda-10.0/targets/x86_64/lib/ -lOpenCL
clDeviceQuery.cpp: In function ‘void clPrintDevInfo(cl_device_id)’:
clDeviceQuery.cpp:54:70: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("  CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:\t%u\n", workitem_dims);
                                                                      ^
clDeviceQuery.cpp:59:115: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("  CL_DEVICE_MAX_WORK_ITEM_SIZES:\t%u / %u / %u \n", workitem_size[0], workitem_size[1], workitem_size[2]);
                                                               ~~~~~~~~~~~~~~~~                                    ^
clDeviceQuery.cpp:59:115: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
clDeviceQuery.cpp:59:115: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
clDeviceQuery.cpp:64:66: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("  CL_DEVICE_MAX_WORK_GROUP_SIZE:\t%u\n", workgroup_size);
                                                                  ^
clDeviceQuery.cpp:131:51: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("\t\t\t2D_MAX_WIDTH\t %u\n", szMaxDims[0]);
                                       ~~~~~~~~~~~~^
clDeviceQuery.cpp:133:56: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("\t\t\t\t\t2D_MAX_HEIGHT\t %u\n", szMaxDims[1]);
                                            ~~~~~~~~~~~~^
clDeviceQuery.cpp:135:55: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("\t\t\t\t\t3D_MAX_WIDTH\t %u\n", szMaxDims[2]);
                                           ~~~~~~~~~~~~^
clDeviceQuery.cpp:137:56: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("\t\t\t\t\t3D_MAX_HEIGHT\t %u\n", szMaxDims[3]);
                                            ~~~~~~~~~~~~^
clDeviceQuery.cpp:139:55: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   printf("\t\t\t\t\t3D_MAX_DEPTH\t %u\n", szMaxDims[4]);
                                           ~~~~~~~~~~~~^

~/Downloads/intel_opencl$  [master] $ ./clDeviceQuery 
clDeviceQuery Starting...

 Error -1001 in clGetPlatformIDs Call!

~/Downloads/intel_opencl$  [master] $ `

**Comment by cdeterman** [comment] 2019-01-14 18:15
The warnings are okay but the script is saying essentially saying that no platforms were found (the Error -1001).  Sorry for so much back and forth but I also forgot about just the `clinfo` call.  Try installing and executing `clinfo`.  Installation I believe should be a simple `apt-get install clinfo`.  

On a separate note, I have been coming across different instances of OpenCL troubles with the NVIDIA 410 driver, see [here](https://devtalk.nvidia.com/default/topic/1043943/linux/opencl-doesn-t-work-with-nvidia-driver-410-xx-415-13-drivers-for-linux/) and [here](https://forum.manjaro.org/t/opencl-not-detecting-after-i-install-410-drivers-for-nvidia/66689/3).  Not sure where the error is necessarily coming from yet.

**Comment by evodevosys** [comment] 2019-01-14 18:36
Actually, I'm not sure I _can_ do that (or at least know how to do this).  When I look at the [CUDA toolkit 9.2 download](https://developer.nvidia.com/cuda-92-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu) there is no Ubuntu 18.04 version.

**Comment by evodevosys** [comment] 2019-01-15 22:44
Sorry for the delay - I missed the 'executing clinfo' part of what you said.  Here is the output:

`sarifkin@rendel:~/Downloads/intel_opencl$  [master] $ clinfo
Number of platforms                               1
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 1.2 CUDA 10.0.206
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
  Platform Extensions function suffix             NV

  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     GeForce GTX 1060 3GB
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 1.2 CUDA
  Driver Version                                  410.78
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Topology (NV)                            PCI-E, 65:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               9
  Max clock frequency                             1835MHz
  Compute Capability (NV)                         6.1
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x64
  Max work group size                             1024
  Preferred work group size multiple              32
  Warp size (NV)                                  32
  Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 0 / 0        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              3162832896 (2.946GiB)
  Error Correction support                        No
  Max memory allocation                           790708224 (754.1MiB)
  Unified memory for Host and Device              No
  Integrated memory (NV)                          No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       4096 bits (512 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        147456 (144KiB)
  Global Memory cache line size                   128 bytes
  Image support                                   Yes
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x32768 pixels
    Max 3D image size                             16384x16384x16384 pixels
    Max number of read image args                 256
    Max number of write image args                16
  Local memory type                               Local
  Local memory size                               49152 (48KiB)
  Registers per block (NV)                        65536
  Max number of constant args                     9
  Max constant buffer size                        65536 (64KiB)
  Max size of kernel argument                     4352 (4.25KiB)
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Kernel execution timeout (NV)                 Yes
  Concurrent copy and kernel execution (NV)       Yes
    Number of async copy engines                  2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [NV]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  Invalid device type for platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform
`

**Comment by cdeterman** [comment] 2019-01-17 18:47
@evodevosys The last part with the `clGetPlatformInfo` was part of the `clinfo` output?  If so, it appears that indeed the OpenCL is not working/connected to the NVIDIA toolkit.

**Comment by evodevosys** [comment] 2019-01-17 21:46
yes, that was part of the output.

**Comment by evodevosys** [comment] 2019-01-17 23:10
In case it is useful, I ran: ` strace -fv ./clDeviceQuery | grep -i opencl` as per the suggestion on [this thread ](https://stackoverflow.com/questions/49512129/error-no-opencl-platforms-found-check-opencl-installation) and got the following output from the grep:

`1 OpenCL Platforms found
 CL_PLATFORM_VERSION:   OpenCL 1.2 CUDA 10.0.206
OpenCL Device Info:
 1 devices found supporting OpenCL on: NVIDIA CUDA
clDeviceQuery, Platform Name = NVIDIA CUDA, Platform Version = OpenCL 1.2 CUDA 10.0.206, NumDevs = 1, Device = GeForce GTX 1060 3GB`

**Comment by evodevosys** [comment] 2019-01-18 01:30
Problem may have been solved based on your OpenCL-NVIDIA communication comment.

I found [this thread](https://devtalk.nvidia.com/default/topic/1036967/linux/unable-to-use-opencl-cuda-on-ubuntu-18-04/) and followed the advice in comment 4 to purge anything nvidia and then reinstall.  

I then tried your clDeviceQuery and that gave me:

> ~/Downloads/intel_opencl$  [master] $ ./clDeviceQuery 
> clDeviceQuery Starting...
> 
> 1 OpenCL Platforms found
> 
>  CL_PLATFORM_NAME: 	NVIDIA CUDA
>  CL_PLATFORM_VERSION: 	OpenCL 1.2 CUDA 10.0.206
> OpenCL Device Info:
> 
>  1 devices found supporting OpenCL on: NVIDIA CUDA
> 
>  ----------------------------------
>  Device GeForce GTX 1060 3GB
>  ---------------------------------
>   CL_DEVICE_NAME: 			GeForce GTX 1060 3GB
>   CL_DEVICE_VENDOR: 			NVIDIA Corporation
>   CL_DRIVER_VERSION: 			410.78
>   CL_DEVICE_TYPE:			CL_DEVICE_TYPE_GPU
>   CL_DEVICE_MAX_COMPUTE_UNITS:		9
>   CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:	3
>   CL_DEVICE_MAX_WORK_ITEM_SIZES:	1024 / 1024 / 64 
>   CL_DEVICE_MAX_WORK_GROUP_SIZE:	1024
>   CL_DEVICE_MAX_CLOCK_FREQUENCY:	1835 MHz
>   CL_DEVICE_ADDRESS_BITS:		64
>   CL_DEVICE_MAX_MEM_ALLOC_SIZE:		754 MByte
>   CL_DEVICE_GLOBAL_MEM_SIZE:		3016 MByte
>   CL_DEVICE_ERROR_CORRECTION_SUPPORT:	no
>   CL_DEVICE_LOCAL_MEM_TYPE:		local
>   CL_DEVICE_LOCAL_MEM_SIZE:		48 KByte
>   CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:	64 KByte
>   CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE
>   CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_PROFILING_ENABLE
>   CL_DEVICE_IMAGE_SUPPORT:		1
>   CL_DEVICE_MAX_READ_IMAGE_ARGS:	256
>   CL_DEVICE_MAX_WRITE_IMAGE_ARGS:	16
> 
>   CL_DEVICE_IMAGE <dim>			2D_MAX_WIDTH	 16384
> 					2D_MAX_HEIGHT	 32768
> 					3D_MAX_WIDTH	 16384
> 					3D_MAX_HEIGHT	 16384
> 					3D_MAX_DEPTH	 16384
>   CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>	CHAR 1, SHORT 1, INT 1, FLOAT 1, DOUBLE 1
> 
> 
> clDeviceQuery, Platform Name = NVIDIA CUDA, Platform Version = OpenCL 1.2 CUDA 10.0.206, NumDevs = 1, Device = GeForce GTX 1060 3GB

I then tried install.packages('gpuR') [so the cran package] and it went through the compiling and gave me the following at the end:

> ** testing if installed package can be loaded
> Number of platforms: 1
> - platform: Apple: OpenCL 1.2 (Nov  2 2015 15:02:14)
>   - context device index: 0
>     - Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz
>   - context device index: 1
>     - GeForce GT 120
> checked all devices
> completed initialization
> * DONE (gpuR)
> 
> The downloaded source packages are in
> 	‘/private/var/folders/80/03mvz5zx4mz02ryy51kjc7km0000gn/T/RtmpWLT5a7/downloaded_packages’
> > library("gpuR", lib.loc="/Library/Frameworks/R.framework/Versions/3.3/Resources/library")
> Number of platforms: 1
> - platform: Apple: OpenCL 1.2 (Nov  2 2015 15:02:14)
>   - context device index: 0
>     - Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz
>   - context device index: 1
>     - GeForce GT 120
> checked all devices
> completed initialization
> gpuR 2.0.0
> 
> Attaching package: ‘gpuR’
> 
> The following objects are masked from ‘package:base’:
> 
>     colnames, pmax, pmin, svd
> 
> > 

which seems like what I'd want.  

Curiously, clinfo still ends with:

> NULL platform behavior
>   clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
>   clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
>   clCreateContext(NULL, ...) [default]            No platform
>   clCreateContext(NULL, ...) [other]              Success [NV]
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  Invalid device type for platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

Thanks very much for helping me track this down.

**Comment by evodevosys** [comment] 2019-01-18 02:00
The problem may be solved!

Based on your comment that there appeared to be a communication error between OpenCL and NVIDIA, I did a web search and came across [this thread](https://devtalk.nvidia.com/default/topic/1036967/unable-to-use-opencl-cuda-on-ubuntu-18-04/)
I followed the instructions in comment #4 to purge all nvidia stuff and then reinstall the CUDA toolkit.  

I then reran your clDeviceQuery and got this output:

```
~/Downloads/intel_opencl$  [master] $ ./clDeviceQuery 
clDeviceQuery Starting...

1 OpenCL Platforms found

 CL_PLATFORM_NAME: 	NVIDIA CUDA
 CL_PLATFORM_VERSION: 	OpenCL 1.2 CUDA 10.0.206
OpenCL Device Info:

 1 devices found supporting OpenCL on: NVIDIA CUDA

 ----------------------------------
 Device GeForce GTX 1060 3GB
 ---------------------------------
  CL_DEVICE_NAME: 			GeForce GTX 1060 3GB
  CL_DEVICE_VENDOR: 			NVIDIA Corporation
  CL_DRIVER_VERSION: 			410.78
  CL_DEVICE_TYPE:			CL_DEVICE_TYPE_GPU
  CL_DEVICE_MAX_COMPUTE_UNITS:		9
  CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:	3
  CL_DEVICE_MAX_WORK_ITEM_SIZES:	1024 / 1024 / 64 
  CL_DEVICE_MAX_WORK_GROUP_SIZE:	1024
  CL_DEVICE_MAX_CLOCK_FREQUENCY:	1835 MHz
  CL_DEVICE_ADDRESS_BITS:		64
  CL_DEVICE_MAX_MEM_ALLOC_SIZE:		754 MByte
  CL_DEVICE_GLOBAL_MEM_SIZE:		3016 MByte
  CL_DEVICE_ERROR_CORRECTION_SUPPORT:	no
  CL_DEVICE_LOCAL_MEM_TYPE:		local
  CL_DEVICE_LOCAL_MEM_SIZE:		48 KByte
  CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:	64 KByte
  CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE
  CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_PROFILING_ENABLE
  CL_DEVICE_IMAGE_SUPPORT:		1
  CL_DEVICE_MAX_READ_IMAGE_ARGS:	256
  CL_DEVICE_MAX_WRITE_IMAGE_ARGS:	16

  CL_DEVICE_IMAGE <dim>			2D_MAX_WIDTH	 16384
					2D_MAX_HEIGHT	 32768
					3D_MAX_WIDTH	 16384
					3D_MAX_HEIGHT	 16384
					3D_MAX_DEPTH	 16384
  CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>	CHAR 1, SHORT 1, INT 1, FLOAT 1, DOUBLE 1


clDeviceQuery, Platform Name = NVIDIA CUDA, Platform Version = OpenCL 1.2 CUDA 10.0.206, NumDevs = 1, Device = GeForce GTX 1060 3GB
```

So that was progress.  
clinfo however, gave the same NULL platform behavior as before:

```
NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [NV]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  Invalid device type for platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform
 
```

Nevertheless, I went ahead and tried installing gpuR from the github repository, and it looks like it worked!

```
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o gpuR.so RcppExports.o chol.o context.o custom_math.o device.o gpuEigenPtr.o gpuMatrix_igemm.o norm.o platform.o set_row_order.o solve.o synchronize.o trunc_gpuMat.o utils-vcl.o utils.o vclPtr.o vienna_blas1.o vienna_blas2.o vienna_blas3.o vienna_eigen.o vienna_qr.o vienna_stats.o vienna_svd.o -lOpenCL -L/usr/lib/R/lib -lR
installing to /home/sarifkin/R/x86_64-pc-linux-gnu-library/3.5/gpuR/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Creating a generic function for 'eigen' from package  'base' in package 'gpuR'
Creating a generic function for '%o%' from package  'base' in package 'gpuR'
Creating a generic function for 'nrow' from package  'base' in package 'gpuR'
Creating a generic function for 'ncol' from package  'base' in package 'gpuR'
Creating a generic function for 'crossprod' from package  'base' in package 'gpuR'
Creating a generic function for 'tcrossprod' from package  'base' in package 'gpuR'
Creating a generic function for 'cov' from package 'stats' in package 'gpuR'
Creating a generic function for 'colSums' from package  'base' in package 'gpuR'
Creating a generic function for 'rowSums' from package 'base' in package 'gpuR'
Creating a generic function for 'colMeans' from package  'base' in package 'gpuR'
Creating a generic function for 'rowMeans' from package  'base' in package 'gpuR'
Creating a generic function for 'dist' from package 'stats'in package 'gpuR'
Creating a generic function for 'diag' from package  'base' in package 'gpuR'
Creating a generic function for 'diag<-' from package  'base' in package 'gpuR'
Creating a generic function for 'det'from package  'base' in package 'gpuR'
Creating a generic function for 'norm' from package  'base' in package 'gpuR'
Creating a generic function for 'qr.R'from package 'base' in package 'gpuR'
Creating a generic function for 'qr.Q' from package'base' in package 'gpuR'
Creating a generic function for'typeof' from package 'base' in package 'gpuR'
Creating a generic function for 'colnames<-' from package'base' in package 'gpuR'
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Number of platforms: 1
- platform: NVIDIA Corporation: OpenCL 1.2 CUDA 10.0.206
  - context device index: 0
    - GeForce GTX 1060 3GB
checked all devices
completed initialization
* DONE (gpuR)
> library(gpuR)
Number of platforms: 1
- platform: NVIDIA Corporation: OpenCL 1.2 CUDA 10.0.206
  - context device index: 0
    - GeForce GTX 1060 3GB
checked all devices
completed initialization
gpuR 2.0.1

Attaching package: 'gpuR'
```

Thanks very much for helping me track this down.

**Comment by cdeterman** [comment] 2019-01-21 18:58
@evodevosys excellent, glad the issue is resolved.  I will close this issue then.

**Closed by cdeterman** 2019-01-21 18:58 UTC
Labels: Installation Help, Linux
