### ISSUE TITLE
Inconsistent results between CPU and GPU matrix multiplication (integer)

### ISSUE THREAD

**Issue by zhewa** [cdeterman/gpuR#140] opened 2018-09-12 17:43 UTC
Hi @cdeterman ,

I recently started doing matrix multiplication in R using GPU and `gpuR`. I found an inconsistency between CPU and GPU matrix multiplication results for integer matrices. Here is an example:

```
library(gpuR)
A <- matrix(sample(1:10, size = 10*1000, replace = TRUE), nrow = 10)
B <- matrix(sample(1:10, size = 1000*10, replace = TRUE), nrow = 1000)

gpuA <- gpuMatrix(A)
gpuB <- gpuMatrix(B)

all.equal(A, gpuA[])
[1] TRUE
all.equal(B, gpuB[])
[1] TRUE

C <- A %*% B
gpuC <- gpuA %*% gpuB

# check if results are equal
all.equal(C, gpuC[])
[1] "Mean relative difference: 0.02626947"
```

This only happens for relatively large integer matrices and not for float matrices or small integer matrices. I also tested this on a Windows 10 desktop with NVIDIA GeForce GTX 1080 GPU and it's having the same discrepency. Is there something I'm not doing right?

```
> gpuInfo()
$deviceName
[1] "Tesla P100-PCIE-16GB"

$deviceVendor
[1] "NVIDIA Corporation"

$numberOfCores
[1] 56

$maxWorkGroupSize
[1] 1024

$maxWorkItemDim
[1] 3

$maxWorkItemSizes
[1] 1024 1024   64

$deviceMemory
[1] 17071734784

$clockFreq
[1] 1328

$localMem
[1] 49152

$maxAllocatableMem
[1] 4267933696

$available
[1] "yes"

$deviceExtensions
 [1] "cl_khr_global_int32_base_atomics"    
 [2] "cl_khr_global_int32_extended_atomics"
 [3] "cl_khr_local_int32_base_atomics"     
 [4] "cl_khr_local_int32_extended_atomics" 
 [5] "cl_khr_fp64"                         
 [6] "cl_khr_byte_addressable_store"       
 [7] "cl_khr_icd"                          
 [8] "cl_khr_gl_sharing"                   
 [9] "cl_nv_compiler_options"              
[10] "cl_nv_device_attribute_query"        
[11] "cl_nv_pragma_unroll"                 
[12] "cl_nv_copy_opts"                     
[13] "cl_nv_create_buffer"                 

$double_support
[1] TRUE
```

**Comment by cdeterman** [comment] 2018-09-14 15:57
@zhewa thanks for this report.  I have confirmed it on my own machine.  Something must be wrong with the integer kernel.  I will need to have a closer look at this.  I suspect it is because the matrices aren't square and the kernel doesn't handle the rectangular shape well.

**Comment by cdeterman** [comment] 2018-09-17 17:19
@zhewa this should be resolved in the `develop` branch now.  My CI is failing because of some time constraints.  Please feel free to install the `develop` branch with `devtools::install_github('cdeterman/gpuR', ref = 'develop')` to test and confirm it works for you.

**Comment by cdeterman** [comment] 2018-09-21 16:29
@zhewa try once again now, I have verified locally that the different sizes are working.  I couldn't quite reproduce your last example as my current GPU is just the basic Intel GPU that came with my laptop (it crashes my browser as it is running the display).

**Comment by zhewa** [comment] 2018-09-21 16:46
@cdeterman Yes, I think it works now. I tried multiplication of integer matrices up to 1 million columns and the results are identical between CPU and GPU. Thanks you.

**Closed** 2019-05-03 18:26 UTC
Labels: bug
