### ISSUE TITLE
Inverse of the matrix

### ISSUE THREAD

**Issue by Dzirik** [cdeterman/gpuR#34] opened 2016-09-07 17:57 UTC
Hello,

you made a nice piece of work! I walked through documentation and could not find an inverse of a matrix.  Missed I something? Or do you plan to implement that?

Thanks for your answer!

**Comment by cdeterman** [comment] 2016-09-07 18:08
Hi @Dzirik, the inverse of a matrix is not currently implemented.  I will make a note to add that functionality as it appears to be supported in the [ViennaCL backend](https://sourceforge.net/p/viennacl/discussion/1143678/thread/ba394d35/) via LU factorization.  

I assume you are referring that you are indeed looking for similar functionality as the `solve` function in base R where it is solving for Ax = B?

**Comment by Dzirik** [comment] 2016-09-07 18:30
You are right, the `solve` equivavent (Ax=b) would be best, as in your link.

**Comment by Dzirik** [comment] 2016-09-07 18:31
You are right, the solve equivavent (Ax=b) would be best, as in your link.

**Comment by Dzirik** [comment] 2016-09-13 14:30
Hello,

thanks for your quick reaction, I tested it shortly today and it works! Just the benchmark results are a bit strange from the time point of view. It seems that `solve()` is much faster for `vclMatrix`, but for `gpuMatrix` the results takes the same time as for ordinary `solve()` (see bellow my results).

I will test it more in the future and let you know.

Thanks for your effort!

```
#data
 A = matrix(rnorm(ORDER^2), nrow=ORDER)
 gpuA = gpuMatrix(A, type="double")
 inGpuA=vclMatrix(rnorm(ORDER^2), nrow=ORDER, ncol=ORDER)

#benchmark invers
  microbenchmark(
    solve(A), 
    solve(gpuA),
    solve(inGpuA),
    list = NULL, 
    times = 10, 
    check = NULL,
    control = list()
  )

#results
Unit: milliseconds
         expr       min           lq               mean         median      uq            max              neval
         solve(A) 6338.3713 6394.2085 6456.7490 6462.6575 6482.2128 6601.2535    10
   solve(gpuA) 6400.9450 6405.5547 6491.6145 6489.2423 6561.7971 6622.5213    10
 solve(inGpuA)  513.7941  524.7209    635.1692  634.2595   693.8229    909.0948    10
```

**Comment by cdeterman** [comment] 2016-09-13 14:43
@Dzirik that is interesting about `gpuMatrix` because I didn't implement a method for that class.  I suspect it is going to the default method and converted to a normal `matrix`.  I am currently working on the `gpuMatrix` implementation.  Hopefully I will have it sometime later today.

**Comment by cdeterman** [comment] 2016-09-15 13:08
@Dzirik I have the `gpuMatrix` implementation locally and was running some preliminary tests and I was seeing different results regarding `vclMatrix` from you.  Before I push anything I want to make sure I didn't inadvertently worsen the performance.  What GPU are you currently using on your machine?  Also, what is the `ORDER` you are using?  It would also be valuable to use a `set.seed` as well for consistency.

**Comment by cdeterman** [comment] 2016-09-26 13:20
@Dzirik Not sure if you have any bandwidth to test this with your GPU workstation but I will likely close this issue soon as it works properly for me.  Thanks.

**Comment by Dzirik** [comment] 2016-09-29 13:28
@cdeterman I am sorry not to respond earlier, I was busy, then on holiday.

I test it and have following error 

Error in .Call("gpuR_cpp_gpuMatrix_solve", PACKAGE = "gpuR", ptrA, ptrB,  : 
  "gpuR_cpp_gpuMatrix_solve" not available for .Call() for package "gpuR"
for both `gpuMatrix`, `vclMatrix`.

Multiplication `%*%` and `svd` work fine.

I am running it on 

- windows  10, release >= 8 x64, build 9200 
- R version 3.3.1 (2016-06-21)/x86_64-w64-mingw32, 
- gpuR version 1.1.4 (I installed it twice, with restarting)
- GPU GeForce GTX TITAN X

**Comment by cdeterman** [comment] 2016-09-29 13:34
@Dzirik now that is very odd.  Did you just reinstall today?  It is working for me locally and on the CI system I am using.  I will check on my Windows machine just to make sure.

**Comment by Dzirik** [comment] 2016-09-29 13:37
I reinstalled it today, some hours ago.

**Comment by cdeterman** [comment] 2016-09-29 14:05
@Dzirik okay, I just reinstalled on my Windows system directly from the github develop branch and it is working without a problem.  Could you please try reinstalling once more and trying again?

```r
devtools::install_github('cdeterman/gpuR', ref = 'develop')
```

**Comment by Dzirik** [comment] 2016-09-29 14:07
Ok, thanks, good to hear, I will try it.

**Comment by Dzirik** [comment] 2016-09-30 08:18
@cdeterman , I finally found where problem was. There was some conflict in calling `gpuR::solve`, maybe from older versions, simple reinslalation did not work. But at the end, unistalling `uninstall.packages` and installing again worked fine.

Thanks for your effort and help!

**Comment by cdeterman** [comment] 2016-09-30 12:29
@Dzirik awesome, good to know about `uninstall.packages` helping.  As always, let me know if you encounter further problems or have other ideas about enhancements in new issues.

**Closed by cdeterman** 2016-09-30 12:29 UTC
Labels: enhancement

**Comment by Dzirik** [comment] 2016-09-30 13:26
@cdeterman , off course, I will work with your library a bit more now, so if st appears, I will let you know.

**Comment by rsettlage** [comment] 2017-04-01 05:19
Hi,
I am seeing some odd behavior on this when comparing the gpuMatrix and vlcMatrix versions of solve.  Essentially I am getting different results on the same system.  I am basically looking at timings on different combinations of solve and crossprod to get at beta_hat

`  set.seed(123456)
    library(gpuR)
    np<-30 #number of predictors
    nr<-100000 #number of observations
    X<-cbind(5,1:nr,matrix(runif((np-1)*nr,0,10),nrow=nr,ncol=(np-1)))
    beta<-matrix(c(1,3,runif(np-1,0,0.2)),ncol=1)
    y<-X%*%beta+matrix(rnorm(nr,0,1),nrow=nr,ncol=1)
    #CPU bound version, we could optimize but lets stay vanilla
    time1<-system.time({
        ms1<-solve(t(X) %*% X) %*% t(X) %*% y
        })
    time2<-system.time({
        ms2<-solve(t(X) %*% X, t(X) %*% y)
        })
    
    time3<-system.time({
        ms3<-solve(crossprod(X), crossprod(X,y))
        })
    #GPU version, GPU pointer to CPU memory!! (gpuMatrix is simply a pointer)
    gpuX = gpuMatrix(X, type="float") #point GPU to matrix
    gpuy = gpuMatrix(y, type="float")
    time4<-system.time({
        ms4<-solve(t(gpuX) %*% gpuX, t(gpuX) %*% gpuy)
    })
    #GPU version, in GPU memory!! (vclMatrix formation is a memory transfer)
    vclX = vclMatrix(X, type="float") #push matrix to GPU
    vcly = vclMatrix(y, type="float")
    time5<-system.time({
        ms5<-solve(t(vclX) %*% vclX, t(vclX) %*% vcly)
    })
    time6<-system.time({
        ms6<-solve(crossprod(vclX), crossprod(vclX,vcly))
    })`

`> head(ms1[1:31])
[1] 0.99750944 3.00000021 0.05695328 0.17499997 0.10258608 0.05325643
> head(ms4[1:31])
[1]  2.0217857  2.9999902 -0.1811712  0.2071967 -0.1656836  0.3810441
> head(ms5[1:31])
[1] NaN NaN NaN NaN NaN NaN
> head(ms6[1:31])
[1]  2.0217857  2.9999902 -0.1811712  0.2071967 -0.1656836  0.3810441`

I am not sure what about the 5th method using the vclMatrix is different.

This is on a Mac, R 3.3.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9                assertive.sets_0.0-3       codetools_0.2-15           assertive.data.us_0.0-1   
 [5] assertive.types_0.0-3      assertive.properties_0.0-4 assertive.base_0.0-7       assertive.models_0.0-1    
 [9] assertive.code_0.0-1       stringi_1.1.2              assertive.strings_0.0-3    assertive.matrices_0.0-1  
[13] assertive.reflection_0.0-4 assertive.data_0.0-1       assertive_0.3-5            assertive.datetimes_0.0-2 
[17] tools_3.3.2                assertive.numbers_0.0-2    assertive.files_0.0-2      assertive.data.uk_0.0-1   
[21] knitr_1.15.1

**Comment by rsettlage** [comment] 2017-04-02 14:20
Looking into this a bit more, I think a) the difference in result is definitely due to precision, and b) the difference between the gpu and vlc methods is likely due to the same.  The difference between 5 and 6 must be because of an overflow error that is handled by doing the compute in parts (i.e. 6) that is not handled when you pass both parts of the solve.

**Comment by cdeterman** [comment] 2017-04-03 19:49
@rsettlage you are correct that the difference between `ms1` and `ms4` is because of precision.  If using `type = 'double'` the results match.  The problem noted in `ms5` is interesting.  I will need to look at this more closely.  I am able to reproduce it so I will let you know if/when I figure out something more.  However, I am opening another issue to address this explicitly as this isn't related to the initial implementation.

**Comment by cdeterman** [comment] 2017-04-21 20:16
@rsettlage I believe the problem should be resolved now.  Please download the 'develop' version to verify `devtools::install_github('cdeterman/gpuR', ref = 'develop')`.

**Comment by rsettlage** [comment] 2017-04-21 22:41
Yes, looks like my gpuMatrix and vclMatrix results match now.

Thanks!
