### ISSUE TITLE
gpuVector cannot be called using ::

### ISSUE THREAD

**Issue by dstanley4** [cdeterman/gpuR#83] opened 2017-05-26 18:17 UTC
If you want use gpuR within another package you need to call functions via ::
Thus, instead of calling gpuVector(c(1,2,3,4,5), length=10,type = "float")
you need to call gpuR::gpuVector(c(1,2,3,4,5), length=10,type = "float").

This works fine for gpuR::gpuMatrix but fails for gpuVector.

Error for gpuVector:
> gpuR::gpuVector(c(1,2,3,4,5), length=10,type = "float")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘gpuVector’ for signature ‘"numeric", "numeric"’

Fine for gpuMatrix:
> gpuR::gpuMatrix(c(1,2,3,4,5,6), nrow=2,ncol=6,type = "float")
An object of class "fgpuMatrix"
Slot "address":
<pointer: 0x101799650>

Slot ".context_index":
[1] 1

Slot ".platform_index":
[1] 1

Slot ".platform":
[1] "Apple"

Slot ".device_index":
[1] 1

Slot ".device":
[1] "HD Graphics 4000"

**Comment by cdeterman** [comment] 2017-05-26 20:21
@dstanley4 I believe this should be resolved by either importing the package as described in this link [here](http://kbroman.org/pkg_primer/pages/depends.html) using either `#' @import` or `#' @importFrom` from roxygen.

**Comment by cdeterman** [comment] 2017-05-30 14:08
@dstanley4 did this solve the problem or is it still failing to export properly?  This shouldn't be a `gpuR` issue but more of a package development issue with R.

**Comment by cdeterman** [comment] 2017-06-01 13:25
@dstanley4 very interesting.  To confirm, this is only a problem with `gpuVector` and everything works fine with `gpuMatrix`?  Regarding the overloaded methods, I thought I had them all default to the `base` or `stats` methods when not using a `gpuR` object.  I will need to have a closer look.  Is this package you are trying to build on github?  I would like to be able to reproduce this myself as well to help you troubleshoot the problem.

**Comment by dstanley4** [comment] 2017-06-01 14:43
I’ll pull an example together for Github in the next week or so - and then let you know.


On Jun 1, 2017, at 9:25 AM, Charles Determan <notifications@github.com<mailto:notifications@github.com>> wrote:


@dstanley4<https://github.com/dstanley4> very interesting. To confirm, this is only a problem with gpuVector and everything works fine with gpuMatrix? Regarding the overloaded methods, I thought I had them all default to the base or stats methods when not using a gpuR object. I will need to have a closer look. Is this package you are trying to build on github? I would like to be able to reproduce this myself as well to help you troubleshoot the problem.

**Comment by cdeterman** [comment] 2018-01-04 21:02
@dstanley4 I am coming back to this issue again and looking at it again it appears that I simply didn't/don't have that specific initialization implemented for `gpuVector`.    Also, the `gpuMatrix` call does work but the elements within it are gibberish.  This is because I haven't handled situations when the number of elements provided in a vector don't match the defined matrix dimensions.  This will need to be fixed but I need to figure out how to handle the recycling effectively.  I think it should be relatively straightforward for vectors but the matrices are complicated because ViennaCL matrices are row-oriented so I will need to think about that a bit.  These points are more relevant to issue #62.

Regardless, you still should be able to use the functions within `gpuR` with the namespace prefix.  I can confirm that the following works.

```r
gpuR::gpuVector(1:6, type = "float")[]
[1] 1 2 3 4 5 6
```

**Comment by cdeterman** [comment] 2018-04-04 19:14
@dstanley4 I noticed this issue is becoming a little dated.  I never noticed an example from you on github so I wanted to know if this is still a problem for you?  I am doing some housekeeping as I want to get the 2.1.0 release of gpuR put together and therefore checking all open issues.  Thanks.

**Closed** 2018-05-21 18:03 UTC
Labels: bug
